### ISSUE TITLE
Define pattern by musical notation beat lengths instead of pauses

### ISSUE THREAD

**Issue by dagjomar** [iver56/clap-detection#3]
As a musician, one might be more used to 'length of notes', instead of 'length of pauses'.

So in the example notes given

![clap](https://cloud.githubusercontent.com/assets/1470603/9700905/a6de8d6a-5415-11e5-81f6-f81e4034a939.png)

Instead of defining the pattern to be [2, 1, 1, 2] as the relative pauses between 'notes',
you could define it in musical beats as [1./4, 1./8, 1./8, 1./4, 1./4]. 

Now, a 'converter' could find the smallest of these fractions, and do multiplications to convert it to the proper pattern format.

**Comment by iver56** [comment]
Good idea :+1:
