### ISSUE TITLE
Which sound card do you use?

### ISSUE THREAD

**Issue by iooops** [iver56/clap-detection#6]
I just encountered an input error with my Aureon Dual sound card.
unable to set number of channels...it said.

So I just wonder which sound card you use. And do you have any recommendation on sound card that works fine on raspberry pi?

**Comment by iver56** [comment]
Hi :)
I've tried a cheap mono USB microphone (without a brand) and Zoom H2n (USB). And if my memory serves me right, I tried M-Audio MobilePre USB as well.

When it comes to the problem with number of channels, README.md has something about that:
https://github.com/iver56/clap-detection#segmentation-fault-or-unable-to-set-number-of-channels-on-soundcard

TLDR; replace `nchnls = 1` with `nchnls = 2` and `aIn in` with `aIn, aIn2 ins` in clap.csd
