### ISSUE TITLE
boost input level possible?

### ISSUE THREAD

**Issue by pauledd** [iver56/clap-detection#7]
Hi

I have a cheap microfone usb-stick but the input level is quite low. 
In alsamixer I can go up to 23.81dB but its still to silent to recognize
my claps. Is it possible to somehow preprocess the input stream somehow 
that it gets amplified? Is it correct to set 0dbfs  = 23 in clap.csd?

**Comment by iver56** [comment]
The csound program should already have some preprocessing that boosts the input level if the signal is weak. See https://github.com/iver56/clap-detection/blob/master/clap.csd#L48
Since it doesn't work well, it may need to be tweaked.

I would not recommend setting `0dbfs = 23` in clap.csd
